#define CONFIG_KEYS_LIST                 \
  X(KCOMP_X, "Compass_X", INT)           \
  X(KCOMP_Y, "Compass_Y", INT)           \
  X(KCOORD_X, "Coords_X", INT)           \
  X(KCOORD_Y, "Coords_Y", INT)           \
  X(KALTITUDE_X, "Altitude_X", INT)      \
  X(KALTITUDE_Y, "Altitude_Y", INT)      \
  X(KSPEED_X, "Speed_X", INT)            \
  X(KSPEED_Y, "Speed_Y", INT)            \
  X(KSUN_X, "Sun_X", INT)                \
  X(KSUN_Y, "Sun_Y", INT)                \
  X(KCOMP_OFFSET_X, "compOfsX", FLOAT)   \
  X(KCOMP_OFFSET_Y, "compOfsY", FLOAT)   \
  X(KMAP_ROT_MODE, "mapRotMode", BOOL)   \
  X(KGPS_SPEED, "gpsBaud", SHORT)        \
  X(KGPS_RATE, "gpsRate", SHORT)         \
  X(KWEB_FILE, "webServer", BOOL)        \
  X(KUSER, "-----", UNKNOWN)             \
  X(KDEF_ZOOM, "defZoom", UINT)          \
  X(KMAP_MODE, "fullScrMap", BOOL)       \
  X(KMAP_VECTOR, "vectMap", BOOL)        \
  X(KMAP_SPEED, "mapSpeed", BOOL)        \
  X(KMAP_SCALE, "mapScale", BOOL)        \
  X(KMAP_COMPASS, "mapComp", BOOL)       \
  X(KMAP_COMP_ROT, "mapCompRot", BOOL)   \
  X(KGPS_TX, "gpsTX", UINT)              \
  X(KGPS_RX, "gpsRX", UINT)              \
  X(KLAT_DFL, "defLAT", DOUBLE)          \
  X(KLON_DFL, "defLON", DOUBLE)          \
  X(KDEF_BRIGT, "defBright", UINT)       \
  X(KVMAX_BATT, "VmaxBatt", FLOAT)       \
  X(KVMIN_BATT, "VminBatt", FLOAT)       \
  X(KTEMP_OFFS, "tempOffs", INT)         \
  X(KDEF_TZ, "defTZ",STRING)             \
  X(KDECL_ANG, "defDecAng", FLOAT)       \
  X(KKALM_FIL, "kalmanFil", BOOL)        \
  X(KKALM_Q, "kalmanQ", FLOAT)           \
  X(KKALM_R, "kalmanR", FLOAT)           \
  X(KCOUNT, "KCOUNT", UNKNOWN)
